# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

if Vagrant.has_plugin? "vagrant-vbguest"
config.vbguest.no_install = true
config.vbguest.auto_update = false
config.vbguest.no_remote = true
end
config.vm.define :streama do |streama|
streama.vm.box = "bento/centos-7"
streama.vm.network :private_network, ip: "192.168.50.4"
streama.vm.hostname = "streama"
end
config.vm.define :cliente do |cliente|
cliente.vm.box = "centos/stream8"
cliente.vm.network :private_network, ip: "192.168.50.2"
cliente.vm.hostname = "cliente"
cliente.vm.network :public_network, use_dhcp_assigned_default_route: true
end
config.vm.define :firewall do |firewall|
firewall.vm.box = "bento/centos-7"
firewall.vm.network :private_network, ip: "192.168.50.5"
firewall.vm.network :public_network, use_dhcp_assigned_default_route: true
firewall.vm.hostname = "firewall"
end
config.vm.define :servidor do |servidor|
servidor.vm.box = "centos/stream8"
servidor.vm.network :private_network, ip: "192.168.50.3"
servidor.vm.hostname = "servidor"
end
config.vm.define :firewall2 do |firewall2|
firewall2.vm.box = "bento/centos-7"
firewall2.vm.network :private_network, ip: "192.168.50.6"
firewall2.vm.network :public_network, use_dhcp_assigned_default_route: true
firewall2.vm.hostname = "firewall"
end

end
